# Generated by Django 2.2.7 on 2019-11-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NoteService', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NoteService.Note'),
        ),
    ]
