# Generated by Django 2.2.7 on 2019-11-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NoteService', '0003_auto_20191114_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_tags',
            field=models.ForeignKey(default='#mynote', on_delete=django.db.models.deletion.CASCADE, to='NoteService.Tag'),
        ),
    ]
