# Generated by Django 2.2.7 on 2019-11-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NoteService', '0004_note_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoteService.Tag'),
        ),
    ]
