# Generated by Django 2.2.7 on 2019-11-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteService', '0005_auto_20191116_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_tags',
        ),
    ]
