# Generated by Django 2.2.7 on 2019-11-16 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NoteService', '0006_remove_note_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='NoteService.Note'),
        ),
    ]
